noSegments = 8

 filename = "stl/domain"

 "body_segments.boundary" = [0, 1, 2, 3, 4, 5, 6, 7]

# BC = 0

 BC.0 = 17616

 BC.1 = 3905

 BC.2 = 3905

 BC.3 = 29051

 BC.4 = 1763

 BC.5 = 29050

 BC.6 = 3905

 BC.7 = 3905
