addedAdaptationSteps=1
outputInitialCondition=true
initialAdaptation.default = true
solvertype.default= "MAIA_UNIFIED"
 executionRecipe = "RECIPE_INTRASTEP"
 solvertype.0 = "MAIA_FINITE_VOLUME"
 solvertype.1 = "MAIA_LEVELSET_SOLVER"

 solverOrder_0 = [0,1]
 solverOrder_1 = [1,0]

 couplerOrder_0 = [1,1]

 adaptationOrder = [0,1]

 recipeMaxNoSteps = 2 # necessary ? length of some array ?
 couplerType_0 = "COUPLER_LS_FV_COMBUSTION"
 solversToCouple_0 = [1,0]
 noCouplers = 1

 solverMethod.default                     = "MAIA_RUNGE_KUTTA_GEQU_PV"
lsSolver.default=true
combustion.default=true
levelSet.default=true


omp_num_threads = 1
 cutOffDirections = [2, 1, 3, 0]
 cutOffBndryIds = [17616, 29051, 1763, 29050]

#=========== SCRATCH ======================================================
 scratchSize = 23.00

#============ MULTISOLVER =================================================
 multiSolverGrid=true
 noDomains = 1
 noHaloLayers = 0
 cellMerging = true

#============ STARTUP SETTINGS GRID GENERATION/FLOW SOLVER RUN ============
 gridGenerator = false
 flowSolver = true
 restartFile = false
 restartTimeStep = 0
 useNonSpecifiedRestartFile = true

#============ GRID GENERATION =============================================
 maxRfnmntLvl = 10
 createBoundaryAtCutoff = true

#============ SOLVER TYPE ===============================================
 noRKSteps = 3
 rkalpha-step = [1.0, 0.25, 0.6666666666666666]
 rungeKuttaOrder = 3
 noSpecies = 1

#============ NUMERICAL SETTINGS FV ====================================
 cfl = 0.7
 timeStepMethod = 17511
 globalUpwindCoefficient = 0.0
 upwindCoefficient = 0.0
 dualTimeStepping = false

#============ LEVEL-SET SOLVER ========================================
 gRKMethod = 1
 nogRKSteps = 3
 grkalpha-step = [1.0, 0.25, 0.6666666666666666]
 levelSetDiscretizationScheme = "UC5"
 reinitMethod = "HCR2_FULLREINIT"

#============ NUMERICAL SETTINGS LEVEL SET ============================
 gBandWidth = 20
 gShadowWidth = 30
 gInnerBound = 10
 computeExtVel = 700
# guarantees interpolation of flow velocity to small level set cells -> guarantees pocket generation
 interpolateFlowFieldToFlameFront = false
 smoothExtVel = true
 extVelIterations = 200
 extVelConvergence =  0.0004
 extVelCFL = 0.35
 minReinitializationSteps = 11
 gReinitIterations = 400
 guaranteeReinit = true
 reinitConvergence = 0.39234919077979401667
 reinitThreshold = 0.0006
 reinitThresholdAvg = 0.009
 reinitCFL = 0.35
 relaxationFactor = 0.5
 reinitInterval = 1
 hyperbolicCurvature = false
 highOrderDeltaFunction = false
 useCorrectedBurningVelocity = false
# filterFlameTubeEdges = false ;
# filterFlameTubeEdgesDistance = 0.4 ;

#============ NUMERICAL SETTINGS COMBUSTION MODEL =======================
 subfilterVariance = 1.0
 totalDamp = true
 curvatureDamp = true
 curvatureDampFactor = 3.0
 sharpDamp = false
 dampingDistanceFlameBase = 0.04118806
 noReactionCells = 0.02636719398989614287
 c0 = 0.5

#============ OUTPUT INTERVALS/SETTINGS ================================
 timeSteps = 20
 solutionInterval = 20
 levelSetSolutionInterval = 20
 residualInterval = 1
 dragOutputInterval = 1000000
 restartInterval = 1000
 outputFormat = "VTU"
 maxIterations = 1
 recordPressure = false
 structuredFlameOutput = false
 structuredFlameOutputLevel = 400
 samplesPerCycle = 100
 samplingStartIteration = 85000
 noSamplingCycles = 6
 writeLevelSetData = false
 outputOffset = 0
 writeLineData = false
 recordFlameFrontPosition = true

#============ DATA SETTINGS ===========================================
 outputDir = "./out/"
 gridInputFileName = "grid.Netcdf"
 geometryInputFileName = "geometry.toml"
 "zone_solvers.first" = 0
 solutionOutput = "./out/"

#============ TESTCASE SETTINGS =======================================
 nDim = 2
 initialCondition = 17516
 Re = 592.159
 Ma = 0.0714
 Pr = 0.72
 gamma = 1.4
 angle = [90, 0]
 plenum = false
 burntUnburntTemperatureRatio = 6.95
 shearLayerStrength = 25.0
# deltaYtemperatureProfile= 0.02078124 ;
# thermalProfileStartFactor= -9999.9 ;
 flameRadiusOffset = 0.00
 referenceTemperature = 300
 realRadiusFlameTube = 0.515
 radiusFlameTube = 0.54
 radiusVelFlameTube = 0.509
 xOffsetFlameTube = 0.0
 yOffsetFlameTube = 0.034
 # markstein length chosen from R2_7/Re..P/pert008T7L1 (th: 0.13694181)
 marksteinLength = 0.16338252
 marksteinLengthPercentage = 0.8
 steadyFlameLength = 3.98428634086723088004
 flameSpeed = 0.00857
 massFlux = false
 laminarFlameThickness = 0.01952
 levelSetBC = "SYMMETRIC"
 levelSetBoundaryCondition = 17516
 levelSetTestCase = 17516
 forcing = true
 Strouhal = -1
# strouhal number based on length ~one (get the strouhl numbers from the DL instability computations)
 neutralFlameStrouhal =  3.1232921
 forcingAmplitude = 0.1

#============ SPONGE BOUNDARY LAYER ======================================
 createSpongeBoundary = true
 spongeLayerLayout = 0
 spongeLayerType = 17515
 noMaxSpongeBndryCells = 76000
 spongeLayerThickness = 1.0
 spongeBndryCndIds = [17616, 1763, 29050, 29051]
 spongeDirections = [2, 3, 0, 1]
 spongeFactor = [1.07, 0.3, 0.3, 0.3]
 sigmaSponge = [150.0 , 150.0 , 150.0 , 150.0]
 spongeReductionFactor = 1.0

#============ MISC SETTINGS ===============================================
 noSolvers = 2
 volumeLimitWall = 0.0
 volumeLimitOther = 0.0

#============ ADAPTATION =================================================
adaptation=true
sensorType = ["INTERFACE"]
sensorWeight = [-1]
adaptationInterval=-1
allowInterfaceRefinement=true
solverAdapts.0=false
solverAdapts.1=true
 noAdaptationSteps = 0
 convergenceCriterion = 1e-12
 timeStepConvergenceCriterion = 1e-6

#============ COLLECTOR SIZES ===========================================
 maxNoBndryCndIds = 10
 maxNoCells = 460000
 maxNoBndryCells = 10000
 maxNoSurfaces = 700000
