#//////////////////////////////////////////////////////////////////////////////

 noSegments = 4  # FIVE SEGMENTS: 4 BOUNDARY SEGMENTS + 1 CYLINDER SEGMENT

 filename.default   = ""   # ROOT SEGMENT NAMES IF ASSIGNED OTHERWISE USE BLANK (opt. use stl/)
 BC.default         = 0    # INITIALISATION OF BC

 filename.0 = "stl/left.stl"
 filename.1 = "stl/upper.stl"
 filename.2 = "stl/right.stl"
 filename.3 = "stl/lower.stl"

#                       1 (SPONGE)
#             _______________________________
#             |                              |
#             |                              |
# (OUTFLOW) 0 |      O         | 2 (OUTFLOW)
#             |                              |
#             |______________________________|
#                       3 (SPONGE)
"body_segments.boundary" = [0,1,2,3]

 BC.0 = 3002  # adiabatic fixed wall conditions    BNDRY CONDITION FOR SEGMENT 0
 BC.1 = 3002  # adiabatic fixed wall conditions     BNDRY CONDITION FOR SEGMENT 1
 BC.2 = 3002  # adiabatic fixed wall conditions   BNDRY CONDITION FOR SEGMENT 2
 BC.3 = 3002  # adiabatic fixed wall conditions      BNDRY CONDITION FOR SEGMENT 3

#//////////////////////////////////////////////////////////////////////////////
