#//////////////////////////////////////////////////////////////////////////////
# MAIA DRIVER OPTIONS:
gridGenerator = true
flowSolver = false       # AND SOLVERS
scratchSize           = 30.0

#//////////////////////////////////////////////////////////////////////
# PHYSICS:
nDim = 2  # 2D PROBLEM

#//////////////////////////////////////////////////////////////////////
# INPUT/OUTPUT:
outputDir = "./out/"               # ROOT DIR OF OUTPUT FILES
gridOutputFileName = "grid.Netcdf"        # GRID INPUT FILE FOR SOLVER
geometryInputFileName = "geometry.toml" # GEOMETRY BINARY FILE

#//////////////////////////////////////////////////////////////////////
# GRID GENERATION:
minLevel = 5  # MIN REFINEMENT LEVEL (CELLS ABOVE THIS LEVEL DELETED)
maxRfnmntLvl = 8            # MAX ALLOWED REFINEMENT LEVEL
maxUniformRefinementLevel = 7      # INITIAL REFINEMENT LEVEL
#localRfnMethod            = 2
#localRfnLvlMethods = "B"
#localMinBoundaryThreshold = 2
#localRfnBoundaryIds = [0,1,2,3]
maxBoundaryRfnLvl = 8        # REFINEMENT LEVEL AT BNDRY CND

#//////////////////////////////////////////////////////////////////////
# MEMORY ALLOCATION:
maxNoCells = 400000     # MAX #OF CELLS ( ~9 * (2^{D})^{Level} )

#//////////////////////////////////////////////////////////////////////
# TO REMOVE;
noDomains = 1        # #of MPI Process (not necessary for Massive Parallel)
