#//////////////////////////////////////////////////////////////////////////////
# MAIA DRIVER OPTIONS:
gridGenerator = true
flowSolver = false       # AND SOLVERS

#//////////////////////////////////////////////////////////////////////
# PHYSICS:
nDim = 2  # 2D PROBLEM

#//////////////////////////////////////////////////////////////////////
# INPUT/OUTPUT:
outputDir = "./out/"               # ROOT DIR OF OUTPUT FILES
gridOutputFileName = "grid.Netcdf"        # GRID INPUT FILE FOR SOLVER
geometryInputFileName = "geometry.toml" # GEOMETRY BINARY FILE

#//////////////////////////////////////////////////////////////////////
# GRID GENERATION:
minLevel = 10  # MIN REFINEMENT LEVEL (CELLS ABOVE THIS LEVEL DELETED)
maxRfnmntLvl = 13             # MAX ALLOWED REFINEMENT LEVEL
maxUniformRefinementLevel = 10 # INITIAL REFINEMENT LEVEL
maxBoundaryRfnLvl = 10 # REFINEMENT LEVEL AT BNDRY CND
localRfnMethod           = 0


#//////////////////////////////////////////////////////////////////////
# MEMORY ALLOCATION:
maxNoCells = 19800000     # MAX #OF CELLS ( ~9 * (2^{D})^{Level} )
scratchSize = 5
#//////////////////////////////////////////////////////////////////////
noDomains = 1        # #of MPI Process (not necessary for Massive Parallel)
