#//////////////////////////////////////////////////////////////////////////////
# MAIA DRIVER OPTIONS:
gridGenerator = true
flowSolver = false       # AND SOLVERS

#//////////////////////////////////////////////////////////////////////
# PHYSICS:
nDim = 2  # 2D PROBLEM

#//////////////////////////////////////////////////////////////////////
# INPUT/OUTPUT:
outputDir = "./out/"               # ROOT DIR OF OUTPUT FILES
gridOutputFileName = "grid.Netcdf"        # GRID INPUT FILE FOR SOLVER
geometryInputFileName = "geometry.toml" # GEOMETRY BINARY FILE

#//////////////////////////////////////////////////////////////////////
# GRID GENERATION:
minLevel = 8  # MIN REFINEMENT LEVEL (CELLS ABOVE THIS LEVEL DELETED)
maxRfnmntLvl = 13             # MAX ALLOWED REFINEMENT LEVEL
maxUniformRefinementLevel = 8 # INITIAL REFINEMENT LEVEL
maxBoundaryRfnLvl = 10 # REFINEMENT LEVEL AT BNDRY CND
localRfnMethod           = 1
localRfnLvlMethods = "RB-RB-R"
localRfnLevelProperties = [0.012, 0.00, 0.00775,
		           -0.10,  -0.10, 0.0046, 0.0002,
                           0.012, 0.00, 0.00765,
			   -0.10,  -0.10, 0.0046, 0.0001,
                           0.012, 0.00, 0.00755]
#localRfnLvlMethods = "R-R-R"
#localRfnLevelProperties = [0.012, 0.00, 0.00775,
#                           0.012, 0.00, 0.00765,
#                           0.012, 0.00, 0.00755]

#localMinBoundaryThreshold = 32
#localRfnBoundaryIds = [4]
#maxBoundaryRfnLvl = 12       # REFINEMENT LEVEL AT BNDRY CND


#//////////////////////////////////////////////////////////////////////
# MEMORY ALLOCATION:
maxNoCells = 19800000     # MAX #OF CELLS ( ~9 * (2^{D})^{Level} )
scratchSize = 5
#//////////////////////////////////////////////////////////////////////
noDomains = 1        # #of MPI Process (not necessary for Massive Parallel)
