#1;95;0c#//////////////////////////////////////////////////////////////////////////////
# MAIA DRIVER OPTIONS:
gridGenerator = false    # ACTIVATE GRID GENERATOR
flowSolver = true       # AND SOLVERS

#//////////////////////////////////////////////////////////////////////
# PHYSICS:
nDim = 2  # 2D PROBLEM
timeSteps = 10000      # #OF TIMESTEPS
Re = 80              # REYNOLDS NUMBER
Ma = 0.2             # MACH NUMBER
gamma = 1.4          # RATIO OF SPECIFIC HEATS
initialCondition = 11212 # INITIAL CONDITION

#//////////////////////////////////////////////////////////////////////
# NUMERICS:
executionRecipe = "RECIPE_BASE"
solvertype.default= "MAIA_UNIFIED"
solvertype.0 = "MAIA_FINITE_VOLUME" # SOLVER TYPE: FINITE VOLUME
# upwindCoefficient = 0           # CHI (UPWIND OF PRESSURE SPLITTING)
solverMethod = "MAIA_RUNGE_KUTTA" # TIME INTEGRATION METHOD: RUNGE KUTTA
cfl = 0.4                       # COURANT NUMBER
cellMerging = false                 # FLUX-REDISTRIBUTION ENABLED
timeStepComputationInterval = 1
fvSystemEquations = "FV_SYSEQN_DETCHEM"
#haloMode = 1
#=========== DETAILED CHEMISTRY  ==========================================
isDetChem = true
hasChemicalReaction = true
reactionMechanism = "ohn.yaml"
phaseName = "gas"
transportModel = "Multi"

noSpecies = 18
#viscousFluxScheme = "FIVE_POINT_MULTISPECIES"
viscousFluxScheme = "FIVE_POINT"

#detailedChemInfTemp = 300
#detailedChemInfDensity =  1.18
#detailedChemInfVel = 0.345
infTemperature = 291.0 #291 #250.0
infVelocity = 3.169690384536243
infPressure = 100000 # 100000 #125000
infSpeciesName = ["H2", "N2", "O2"]
infSpeciesMassFraction = [ 0.01730349309146262, 0.7538092820013447, 0.2288872249071927 ]

laminarFlameSpeedFactor = 1.0 
#//////////////////////////////////////////////////////////////////////
#CUT-OFF
cutOff = 1
cutOffMethod = "B"
cutOffCoordinates = [-0.015, -1.0, 0.045, 1.0]

cutOffcbc = true

createBoundaryAtCutoff = true

cutOffDirections = [0, 1]
cutOffBndryIds = [1261, 109900]
cbcRelaxation = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]

bc1251ForcingAmplitude = 0.0
bc1251ForcingWavelength = 0.08
bc1251ForcingDirection = 0

#//////////////////////////////////////////////////////////////////////////////
# LOAD BALANCING

balance = true # activate load balancing
loadBalancingMode = 0 # use weighting mode
#testDynamicLoadBalancing = true # for testcases
loadBalancingInterval = 10
forceLoadBalancing = true

weightFvBndryCells = true
weightFvCutOffCells = false
weightFvBc1601 = false
#=========== ADAPTATION ===================
maxRfnmntLvl = 13            # MAX ALLOWED REFINEMENT LEVEL
adaptation = false
adaptationInterval = 2
sensorWeight = [1.0, -1.0]
sensorType = ["DERIVATIVE", "BAND"]
sensorDerivativeVariables = [4]
allowInterfaceRefinement = true
initialAdaptation = false
mbBandWidth = [10, 10]
smoothingLayers = 10
addedAdaptationSteps = 2
checkRefinementHoles = true
#=========== DETAILED CHEMISTRY  ONE DIMENSIONAL SOLVER ===================
gridRatio = 5.0
gridSlope = 0.5 # 0.4
gridCurve = 0.3 # 0.3
gridPrune = -0.00005
domainLength = 0.03
noGridPoints = 10
equivalenceRatio = 0.6
oneDRelError = 0.01

#============ SOLVER TYPE ==============================================
noRKSteps = 5
rkalpha-step = [0.25, 0.16666666666, 0.375, 0.5, 1.0]
rungeKuttaOrder = 2
globalUpwindCoefficient = 0.05
upwindCoefficient = 0.5

#//////////////////////////////////////////////////////////////////////
# INPUT/OUTPUT:
outputDir = "./out/"               # ROOT DIR OF OUTPUT FILES
solutionOutput = "./out/"          # ROOT DIR FOR SOLUTION OUTPUT
gridInputFileName = "grid.Netcdf"         # GRID GENERATOR OUTPUT FILE
geometryInputFileName = "geometry.toml" # GEOMETRY BINARY FILE
solutionInterval = 500            # OUTPUT INTERVAL IN TIMESTEPS
residualInterval = 1               # RESIDUAL INTERVAL
dragOutputInterval = 10000             # FORCE COEFFICIENTS

createSpongeBoundary = false
#//////////////////////////////////////////////////////////////////////
# BOUNDARY CONDITIONS:
maxNoBndryCndIds = 4     # MAX #OF BOUNDARY CONDITIONS

#//////////////////////////////////////////////////////////////////////

#//////////////////////////////////////////////////////////////////////
# MEMORY ALLOCATION:
maxNoCells = 170000 #7380     # MAX #OF CELLS ( ~9 * (2^{D})^{Level} )
maxNoBndryCells = 200000 #4120 # MAX #OF BOUNDARY CELLS
maxNoSurfaces = 388000  # MAX #OF SURFACES ( ~3 * maxNoCells )
scratchSize = 55
#//////////////////////////////////////////////////////////////////////
noSolvers = 1
noDomains = 12        # #of MPI Process (not necessary for Massive Parallel)
restartTimeStep = 2300
restartFile = false #true
restartInterval = 250
useNonSpecifiedRestartFile = false #false #true
timeStepMethod = 1
noHaloLayers = 2
writeOutData = 0

#sensorBandRefinement = true
sensorBandAdditionalLayers = 80

detChemExtendedOutput = false
#//////////////////////////////////////////////////////////////////////////////
