#//////////////////////////////////////////////////////////////////////////////
# MAIA DRIVER OPTIONS:
gridGenerator = true
flowSolver = false       # AND SOLVERS

#//////////////////////////////////////////////////////////////////////
# PHYSICS:
nDim = 2  # 2D PROBLEM

#//////////////////////////////////////////////////////////////////////
# INPUT/OUTPUT:
outputDir = "./out/"               # ROOT DIR OF OUTPUT FILES
gridOutputFileName = "grid.Netcdf"        # GRID INPUT FILE FOR SOLVER
geometryInputFileName = "geometry.toml" # GEOMETRY BINARY FILE

#//////////////////////////////////////////////////////////////////////
# GRID GENERATION:
minLevel = 7  # MIN REFINEMENT LEVEL (CELLS ABOVE THIS LEVEL DELETED)
maxRfnmntLvl = 13             # MAX ALLOWED REFINEMENT LEVEL
maxUniformRefinementLevel = 8 # INITIAL REFINEMENT LEVEL
maxBoundaryRfnLvl = 11  # REFINEMENT LEVEL AT BNDRY CND
localRfnMethod           = 1
localRfnLvlMethods = "BBB-BBB-BBB"
localRfnLevelProperties = [-0.01, -0.01, 0.09, 0.0007,
                           -0.01, 0.0293, 0.09, 0.04,
			    0.043, -0.01, 0.048, 0.09,
		           -0.01, -0.01, 0.09, 0.0007,
                           -0.01, 0.0293, 0.09, 0.04,
                           0.043, -0.01, 0.048, 0.09,
			   -0.01, -0.01, 0.09, 0.0007,
                           -0.01, 0.0293, 0.09, 0.04,
                            0.043, -0.01, 0.048, 0.09]
#localMinBoundaryThreshold = 2
#localRfnBoundaryIds = [1,3]


#//////////////////////////////////////////////////////////////////////
# MEMORY ALLOCATION:
maxNoCells = 19800000     # MAX #OF CELLS ( ~9 * (2^{D})^{Level} )
scratchSize = 5
#//////////////////////////////////////////////////////////////////////
noDomains = 1        # #of MPI Process (not necessary for Massive Parallel)
